/// Partially generated by bindgen, with setjmp stuff stripped out
use setjmp::sigjmp_buf;
unsafe extern "C" {
    pub static mut PG_exception_stack: *mut sigjmp_buf;
}
unsafe extern "C" {
    pub fn throws();
}
unsafe extern "C" {
    pub fn maybe_throws(x: ::std::os::raw::c_int, dothrow: bool) -> ::std::os::raw::c_int;
}
